---
#################################################################################################################
# MATLAB Installer Role Default Variables
#
# Purpose: Default configuration variables for MATLAB installation role
# Environment: Secure airgapped environments with STIG compliance
# Target: Ubuntu 22.04 and RHEL8 workstations (x86_64)
#
# Security Notes:
# - Sensitive variables should be stored in Ansible Vault
# - File permissions follow security best practices
# - All paths use absolute references for security
#
# Author: Michael Angel
# Date: 2025-09-17
# Version: 1.1
#################################################################################################################

# Installation Configuration
matlab_version: "R2025a"
matlab_install_root: "/usr/local/MATLAB"
matlab_symlink_path: "/usr/local/bin"
matlab_temp_dir: "/tmp/matlab_install"

# Security and Compliance Settings
matlab_enforce_checksums: true
matlab_audit_logging: true
matlab_secure_permissions: true
matlab_stig_compliance: true

# File and Directory Permissions (STIG compliant)
matlab_dir_mode: "0755"
matlab_file_mode: "0644"
matlab_exec_mode: "0755"
matlab_secure_dir_mode: "0750"

# Installation Source Configuration
# These should be customized per environment
matlab_installer_source: "/opt/software/matlab"
matlab_installer_filename: "matlab_{{ matlab_version }}_glnxa64.zip"
matlab_docs_source: "/opt/software/matlab/documentation"
matlab_docs_filename: "matlab_{{ matlab_version }}_help.tar.gz"

# License Configuration
matlab_license_type: "network"
matlab_license_server: "license.example.local"
matlab_license_port: "27000"
matlab_license_file: ""
matlab_file_installation_key: "YOUR_INSTALLATION_KEY"

# Installation Profiles
# Choose installation profile: "standard" or "full" (default: "full")
matlab_installation_profile: "full"

# Standard Profile - Essential toolboxes for most engineering work
matlab_install_products_standard:
  - "MATLAB"
  - "Simulink"
  - "Control_System_Toolbox"
  - "Signal_Processing_Toolbox"
  - "Image_Processing_Toolbox"
  - "Statistics_and_Machine_Learning_Toolbox"
  - "Optimization_Toolbox"
  - "Symbolic_Math_Toolbox"
  - "Curve_Fitting_Toolbox"
  - "DSP_System_Toolbox"
  - "Communications_Toolbox"
  - "Computer_Vision_Toolbox"
  - "Deep_Learning_Toolbox"
  - "Parallel_Computing_Toolbox"
  - "MATLAB_Coder"
  - "Simulink_Coder"
  - "Stateflow"

# Full Profile - All Available Products and Toolboxes
matlab_install_products_full:
  - "MATLAB"
  - "Simulink"
  - "5G_Toolbox"
  - "AUTOSAR_Blockset"
  - "Aerospace_Blockset"
  - "Aerospace_Toolbox"
  - "Antenna_Toolbox"
  - "Audio_Toolbox"
  - "Automated_Driving_Toolbox"
  - "Bioinformatics_Toolbox"
  - "Communications_Toolbox"
  - "Computer_Vision_Toolbox"
  - "Control_System_Toolbox"
  - "Curve_Fitting_Toolbox"
  - "DSP_System_Toolbox"
  - "Data_Acquisition_Toolbox"
  - "Database_Toolbox"
  - "Datafeed_Toolbox"
  - "Deep_Learning_HDL_Toolbox"
  - "Deep_Learning_Toolbox"
  - "Econometrics_Toolbox"
  - "Embedded_Coder"
  - "Filter_Design_HDL_Coder"
  - "Financial_Instruments_Toolbox"
  - "Financial_Toolbox"
  - "Fixed_Point_Designer"
  - "Fuzzy_Logic_Toolbox"
  - "GPU_Coder"
  - "Global_Optimization_Toolbox"
  - "HDL_Coder"
  - "HDL_Verifier"
  - "Image_Acquisition_Toolbox"
  - "Image_Processing_Toolbox"
  - "Industrial_Communication_Toolbox"
  - "Instrument_Control_Toolbox"
  - "LTE_Toolbox"
  - "Lidar_Toolbox"
  - "MATLAB_Coder"
  - "MATLAB_Compiler"
  - "MATLAB_Compiler_SDK"
  - "MATLAB_Parallel_Server"
  - "MATLAB_Production_Server"
  - "MATLAB_Report_Generator"
  - "MATLAB_Web_App_Server"
  - "Mapping_Toolbox"
  - "Mixed_Signal_Blockset"
  - "Model_Predictive_Control_Toolbox"
  - "Motor_Control_Blockset"
  - "Navigation_Toolbox"
  - "Optimization_Toolbox"
  - "Parallel_Computing_Toolbox"
  - "Partial_Differential_Equation_Toolbox"
  - "Phased_Array_System_Toolbox"
  - "Powertrain_Blockset"
  - "Predictive_Maintenance_Toolbox"
  - "RF_Blockset"
  - "RF_PCB_Toolbox"
  - "RF_Toolbox"
  - "ROS_Toolbox"
  - "Radar_Toolbox"
  - "Reinforcement_Learning_Toolbox"
  - "Requirements_Toolbox"
  - "Risk_Management_Toolbox"
  - "Robotics_System_Toolbox"
  - "Robust_Control_Toolbox"
  - "Satellite_Communications_Toolbox"
  - "Sensor_Fusion_and_Tracking_Toolbox"
  - "SerDes_Toolbox"
  - "Signal_Processing_Toolbox"
  - "SimBiology"
  - "SimEvents"
  - "Simscape"
  - "Simscape_Driveline"
  - "Simscape_Electrical"
  - "Simscape_Fluids"
  - "Simscape_Multibody"
  - "Simulink_3D_Animation"
  - "Simulink_Check"
  - "Simulink_Coder"
  - "Simulink_Control_Design"
  - "Simulink_Coverage"
  - "Simulink_Design_Optimization"
  - "Simulink_Design_Verifier"
  - "Simulink_Desktop_Real_Time"
  - "Simulink_PLC_Coder"
  - "Simulink_Real_Time"
  - "Simulink_Report_Generator"
  - "Simulink_Requirements"
  - "Simulink_Test"
  - "SoC_Blockset"
  - "Spreadsheet_Link"
  - "Stateflow"
  - "Statistics_and_Machine_Learning_Toolbox"
  - "Symbolic_Math_Toolbox"
  - "System_Identification_Toolbox"
  - "Text_Analytics_Toolbox"
  - "UAV_Toolbox"
  - "Vehicle_Dynamics_Blockset"
  - "Vehicle_Network_Toolbox"
  - "Vision_HDL_Toolbox"
  - "WLAN_Toolbox"
  - "Wavelet_Toolbox"

# Set active product list based on installation profile
matlab_install_products: "{{ matlab_install_products_full if matlab_installation_profile == 'full' else matlab_install_products_standard }}"

# Silent Installation Configuration
matlab_silent_install: true
matlab_accept_license: true
matlab_create_desktop_shortcuts: true
matlab_install_documentation: true

# System Integration
matlab_update_path: true
matlab_create_module_file: false
matlab_module_path: "/usr/share/modules/modulefiles"

# User Configuration
matlab_default_users: []
matlab_create_user_configs: true
matlab_user_config_template: "matlab_startup.m.j2"

# Cleanup Configuration
matlab_cleanup_temp: true
matlab_cleanup_installer: false
matlab_keep_logs: true
matlab_log_retention_days: 30

# Validation and Health Checks
matlab_verify_installation: true
matlab_run_basic_test: true
matlab_test_timeout: 300

# OS-Specific Package Requirements
matlab_ubuntu_packages:
  - "libxss1"
  - "libxtst6"
  - "libxrandr2"
  - "libasound2-dev"
  - "libpangocairo-1.0-0"
  - "libatk1.0-0"
  - "libcairo-gobject2"
  - "libgtk-3-0"
  - "libgdk-pixbuf2.0-0"
  - "libx11-xcb1"
  - "libxcomposite1"
  - "libxcursor1"
  - "libxdamage1"
  - "libxfixes3"
  - "libxi6"
  - "libxrender1"
  - "libxtst6"
  - "ca-certificates"
  - "libnss3"

matlab_rhel_packages:
  - "alsa-lib"
  - "atk"
  - "cairo"
  - "cairo-gobject"
  - "fontconfig"
  - "gdk-pixbuf2"
  - "glib2"
  - "gtk3"
  - "libX11"
  - "libXcomposite"
  - "libXcursor"
  - "libXdamage"
  - "libXext"
  - "libXfixes"
  - "libXft"
  - "libXi"
  - "libXinerama"
  - "libXrandr"
  - "libXrender"
  - "libXScrnSaver"
  - "libXtst"
  - "pango"
  - "zlib"

# Checksum Validation
# These should be updated for each MATLAB version
matlab_installer_checksums:
  R2025a:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_INSTALLER_R2025a"
  R2024b:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_INSTALLER_R2024b"
  R2024a:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_INSTALLER_R2024a"
  R2023b:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_INSTALLER"

matlab_docs_checksums:
  R2025a:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_DOCS_R2025a"
  R2024b:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_DOCS_R2024b"
  R2024a:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_DOCS_R2024a"
  R2023b:
    sha256: "PLACEHOLDER_CHECKSUM_UPDATE_FOR_ACTUAL_DOCS"

# Error Handling
matlab_max_retries: 3
matlab_retry_delay: 10
matlab_fail_on_error: true

# Essential Variables
# MATLAB Version Information
matlab_supported_versions:
  - "R2025a"
  - "R2024b"
  - "R2024a"
  - "R2023b"

# Installation Requirements
matlab_minimum_requirements:
  disk_space_gb: 30
  memory_mb: 4096

# Network Configuration
matlab_network_ports:
  license_server: 27000
  license_vendor: 27001

# License Types
matlab_license_types:
  - "network"
  - "file"
  - "standalone"

# Environment Variables
matlab_env_vars:
  MATLAB_ROOT: "{{ matlab_install_root }}"
  MATLAB_PREFDIR: "{{ matlab_install_root }}/toolbox/local"
  MATLAB_LOG_DIR: "/var/log/matlab"

# Validation Commands
matlab_validation_commands:
  basic_test: "disp('MATLAB validation test'); exit"
  license_test: "license('test'); exit"